// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524145003_AddAdresseToBestilling")]
    partial class AddAdresseToBestilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyMvcApp.Models.Bestilling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DatoLevert")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatoMontering")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrunnAvRetur")
                        .HasColumnType("text");

                    b.Property<string>("InfoOmVare")
                        .HasColumnType("text");

                    b.Property<bool>("KastetUt")
                        .HasColumnType("boolean");

                    b.Property<bool>("KundeInformert")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("OppdragStartet")
                        .HasColumnType("boolean");

                    b.Property<bool>("OutletLagtUt")
                        .HasColumnType("boolean");

                    b.Property<string>("Plassering")
                        .HasColumnType("text");

                    b.Property<string>("RefNo")
                        .HasColumnType("text");

                    b.Property<string>("Selger")
                        .HasColumnType("text");

                    b.Property<DateTime>("SendesFraLager")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Solgt")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Varegruppe")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bestillinger");
                });
#pragma warning restore 612, 618
        }
    }
}
